# Generated by Django 2.2.6 on 2019-10-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(help_text='Название арендуемого места', max_length=40)),
                ('place_adress', models.TextField(help_text='Адрес места')),
                ('place_area', models.TextField(help_text='Рамки по площади')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_second_name', models.CharField(help_text='Резервное поле для отображения', max_length=50)),
                ('info_maplink', models.TextField(help_text='Ссылка на карту')),
                ('info_price', models.TextField(help_text='Расценки')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Area.Place')),
            ],
        ),
    ]
