# Generated by Django 2.2.6 on 2019-11-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_img',
            field=models.TextField(default='#', help_text='Ссылка на картинку', max_length=150),
        ),
    ]
